### ISSUE TITLE
Gitlab spike

### ISSUE THREAD

**Issue by Grandmagic13** [Grandmagic13/GamePlaceholder#3]
- Check if gitlab has all useful github functionalities when hosted on server
- Check if gitlab supports waffle board
- Check if gitlab supports travis CI & C++/UE4 testing

**Comment by Grandmagic13** [comment]
- Vetettem egy pillantást a gitlabba
- Sok hasznos funkcionalitása van, viszont vannak olyanok amiket jó lenne használni, és csak enterprise alatt érhetőek el, mint:
    - Issue Boards with Milestones
    -  Related Issues
    -  Burndown charts
    -  Multiple assignees for issues
    -  Merge request approvals (multiple)
    -  Restrict push and merge access to certain users
    -  Code Quality
    -  Multiple approvals in code review
    -  Push rules
  @Pluci ezekre a fentiekre a helyedben majd vetnék egy pillantást
- Vélhetően nagyon sok szopás lesz vele hogy összelőjük és időbe is kerül #Devops
- Nem biztos hogy elég triviális config (HDD+router) az üzemeltetéshez
- Maximálisan az EEP verziót lehetne kihasználni ami 3.25$/fő
- Bukjuk vele a Waffle-t a built in taskboardért
- Saját CI van amivel munka van / saját Jenkinsre kell kivezetni amivel munka van.

**Comment by Katsusenpai** [comment]
Igen gondolkodtam rajta én is. Szerintem most evvel ne szórakozzunk, egyelőre használjuk az ingyenes githubot, és mikor majd olyan dolgok lesznek, akkor átváltunk. Mig átpakolásszuk a cuccokat addig sem fog megállni szerintem, legfeljebb fájl szinten nem lesz változás, de addig is tanulni, vagy storyt kidolgozni lehet.

**Comment by Grandmagic13** [comment]
Nem igazán lesz kapacitásunk tanulni, mert akkor Frambin kívül hármónk devopsolni fog ezen valószínűleg... Legfeljebb Frambi addig kap 2D/3D feladatot vagy mást. Minden esetre nem biztos hogy most kellene kitalálni ezt. Illetve ha tényleg pénzt akarunk ettől a projekttől akkor még gitlab esetén sem vagyok feltétlen amondó hogy a havi 3-10-17 dolláron kellene spórolni ami miatt a toolokkal szopni kell. Ha meg mindent ingyenesen akarunk akkor lehet hogy open source szemlélettel is kellene hozzáállni, mert a) a kutyát nem érdekli hogy mit fejlesztünk, b) az ingyenes toolokat (CI integráció, taskboard, management toolok) azzal a feltétellel biztosítják ingyen hogy a termék nyitott. Privát repohoz semmi nem ad CI-t ami már egy hatalmas szopás devops oldalon. Viszont félkész/negyedkész public repot bármikor el lehet mozgatni és kitörölni webről a faszba és akkor senki sem lesz az okosabb. Sztem ezt a köv synchre ismét felrakom napirendi pontként.

**Comment by Grandmagic13** [comment]
UI.: Gitlab SaaS hosting lehet a legolcsóbb módszer az éves szerverbérlés/privát repo/gitfunkcionalitás megoldására. Létezik free private hostingja a CE editionnel, míg havi 4 dollár/user az EEP hostolása, 10GBra limitált, egyéb irányban unlimited repo hostinggal. Ez elég jó dealnek tűnik, és akár indíthatjuk magunkat az ingyenessel, és könnyedén átállhatunk fizetős modellre ha kell. Ezt érdemes megvitatni
